language:
    node_js
node_js:
    - 0.8
    - 0.9
script:
    # We want to gate on passing tests and a successful build
    - bower install
    - cp -R bower_components app/
    - grunt test --verbose